[package]
name = "Rust_Rocker_Web_Api"
version = "0.1.0"
authors = ["Toheeb Adesokan <Toheeb Adesokan@DESKTOP-9CELES0>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
